import type { Article, SectionConfig } from "./types";

const today = new Date().toISOString().split("T")[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split("T")[0];

export const MOCK_ARTICLES: Article[] = [
  {
    id: "1",
    date: today,
    title: "How I Built a Full-Stack App with Claude Code in 2 Hours",
    author: "Simon Willison",
    url: "https://simonwillison.net/2026/Mar/10/claude-code-fullstack/",
    imageUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=450&fit=crop",
    source: "substack",
    sourceName: "Simon Willison's Weblog",
    category: "claude-code",
    summary: "Simon walks through building a complete Next.js app using only Claude Code prompts. Covers database setup, API routes, and deployment — all without leaving the terminal.",
    score: 10,
    scrapedAt: new Date(Date.now() - 3600000).toISOString(),
    status: "featured",
  },
  {
    id: "2",
    date: today,
    title: "The Hidden Power of Claude Code's Multi-File Editing",
    author: "Swyx",
    url: "https://swyx.io/claude-code-multi-file",
    imageUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=450&fit=crop",
    source: "substack",
    sourceName: "Latent Space",
    category: "claude-code",
    summary: "Swyx explores how Claude Code handles complex refactors across dozens of files simultaneously. Includes benchmarks against Cursor and Copilot for large-scale changes.",
    score: 9,
    scrapedAt: new Date(Date.now() - 7200000).toISOString(),
    status: "new",
  },
  {
    id: "3",
    date: today,
    title: "Claude Code + MCP: Building Custom Tool Integrations",
    author: "Anthropic Team",
    url: "https://docs.anthropic.com/claude-code-mcp-tutorial",
    imageUrl: "https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&h=450&fit=crop",
    source: "blog",
    sourceName: "Anthropic Blog",
    category: "claude-code",
    summary: "Official tutorial on connecting Claude Code to external services via Model Context Protocol. Step-by-step guide for building your own MCP server.",
    score: 9,
    scrapedAt: new Date(Date.now() - 10800000).toISOString(),
    status: "new",
  },
  {
    id: "4",
    date: today,
    title: "Why AI Coding Assistants Are Replacing Stack Overflow",
    author: "Ben Thompson",
    url: "https://stratechery.com/2026/ai-coding-assistants/",
    imageUrl: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800&h=450&fit=crop",
    source: "blog",
    sourceName: "Stratechery",
    category: "ai-tools",
    summary: "Ben analyzes the shift from search-based coding help to AI pair programming. Data shows 60% fewer Stack Overflow visits among developers using Claude Code or Cursor daily.",
    score: 8,
    scrapedAt: new Date(Date.now() - 14400000).toISOString(),
    status: "new",
  },
  {
    id: "5",
    date: today,
    title: "Building a CLI Tool with Claude Code: A Step-by-Step Tutorial",
    author: "Julia Evans",
    url: "https://jvns.ca/blog/2026/03/10/cli-with-claude-code/",
    imageUrl: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&h=450&fit=crop",
    source: "blog",
    sourceName: "Julia Evans",
    category: "tutorials",
    summary: "Julia's trademark clear writing style applied to building a complete CLI tool using Claude Code. Covers argument parsing, error handling, and testing.",
    score: 8,
    scrapedAt: new Date(Date.now() - 18000000).toISOString(),
    status: "new",
  },
  {
    id: "6",
    date: today,
    title: "Cursor vs Claude Code vs GitHub Copilot: 2026 Comparison",
    author: "Fireship",
    url: "https://fireship.io/lessons/ai-code-editors-2026/",
    imageUrl: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&h=450&fit=crop",
    source: "blog",
    sourceName: "Fireship",
    category: "ai-tools",
    summary: "Head-to-head comparison of the three major AI coding tools. Claude Code wins on complex multi-file tasks; Cursor leads in inline suggestions; Copilot best for autocomplete.",
    score: 7,
    scrapedAt: new Date(Date.now() - 21600000).toISOString(),
    status: "new",
  },
  {
    id: "7",
    date: today,
    title: "How to Use Claude Code Skills for Repeatable Workflows",
    author: "Thorsten Ball",
    url: "https://thorstenball.com/blog/2026/03/10/claude-code-skills/",
    imageUrl: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&h=450&fit=crop",
    source: "blog",
    sourceName: "Thorsten Ball",
    category: "claude-code",
    summary: "Deep dive into Claude Code's skill system. Shows how to create custom SKILL.md files that encode your team's best practices into repeatable workflows.",
    score: 7,
    scrapedAt: new Date(Date.now() - 25200000).toISOString(),
    status: "new",
  },
  {
    id: "8",
    date: today,
    title: "Anthropic Launches Claude 4.6 with Enhanced Coding Abilities",
    author: "Reuters",
    url: "https://reuters.com/technology/anthropic-claude-4-6-launch-2026-03-10/",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=450&fit=crop",
    source: "news",
    sourceName: "Reuters",
    category: "news",
    summary: "Anthropic releases Claude 4.6 Opus and Sonnet models with significant improvements in code generation, debugging, and multi-step reasoning tasks.",
    score: 7,
    scrapedAt: new Date(Date.now() - 28800000).toISOString(),
    status: "new",
  },
  {
    id: "9",
    date: yesterday,
    title: "Automating Database Migrations with Claude Code",
    author: "Kent C. Dodds",
    url: "https://kentcdodds.com/blog/claude-code-migrations",
    imageUrl: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&h=450&fit=crop",
    source: "blog",
    sourceName: "Kent C. Dodds",
    category: "tutorials",
    summary: "Practical guide to using Claude Code for generating and reviewing database migration scripts. Includes safety patterns for production deployments.",
    score: 6,
    scrapedAt: new Date(Date.now() - 43200000).toISOString(),
    status: "new",
  },
  {
    id: "10",
    date: yesterday,
    title: "The State of AI-Assisted Development in 2026",
    author: "GitHub Blog",
    url: "https://github.blog/2026-03-09-state-of-ai-development/",
    imageUrl: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&h=450&fit=crop",
    source: "blog",
    sourceName: "GitHub Blog",
    category: "ai-tools",
    summary: "GitHub's annual survey reveals 78% of professional developers now use AI coding tools daily. Claude Code and Cursor lead in satisfaction ratings.",
    score: 6,
    scrapedAt: new Date(Date.now() - 50400000).toISOString(),
    status: "new",
  },
  {
    id: "11",
    date: yesterday,
    title: "Testing Strategies When AI Writes Your Code",
    author: "Martin Fowler",
    url: "https://martinfowler.com/articles/ai-testing-strategies.html",
    imageUrl: "https://images.unsplash.com/photo-1576444356170-66073fbf1a4e?w=800&h=450&fit=crop",
    source: "blog",
    sourceName: "Martin Fowler",
    category: "tutorials",
    summary: "Martin Fowler explores how testing practices must evolve when AI generates significant portions of your codebase. Proposes a new testing pyramid for AI-assisted development.",
    score: 5,
    scrapedAt: new Date(Date.now() - 57600000).toISOString(),
    status: "new",
  },
  {
    id: "12",
    date: yesterday,
    title: "Open Source AI Coding Tools to Watch in 2026",
    author: "Hacker News",
    url: "https://news.ycombinator.com/item?id=39012345",
    imageUrl: "",
    source: "news",
    sourceName: "Hacker News",
    category: "ai-tools",
    summary: "Community-curated list of emerging open-source alternatives to commercial AI coding assistants. Includes local-first tools that run models on your own hardware.",
    score: 5,
    scrapedAt: new Date(Date.now() - 64800000).toISOString(),
    status: "new",
  },
];

export const MOCK_CONFIG: SectionConfig[] = [
  {
    sectionName: "Top Picks",
    sourceFilter: "",
    categoryFilter: "",
    minScore: 8,
    maxArticles: 3,
    sortOrder: 1,
    displayStyle: "hero",
    enabled: true,
  },
  {
    sectionName: "Claude Code",
    sourceFilter: "",
    categoryFilter: "claude-code",
    minScore: 5,
    maxArticles: 10,
    sortOrder: 2,
    displayStyle: "grid",
    enabled: true,
  },
  {
    sectionName: "AI Tools",
    sourceFilter: "",
    categoryFilter: "ai-tools",
    minScore: 5,
    maxArticles: 8,
    sortOrder: 3,
    displayStyle: "grid",
    enabled: true,
  },
  {
    sectionName: "Worth Reading",
    sourceFilter: "",
    categoryFilter: "",
    minScore: 5,
    maxArticles: 10,
    sortOrder: 4,
    displayStyle: "list",
    enabled: true,
  },
];
